const ROLES = Object.freeze({
  VIEWER: "viewer",
  ANALYST: "analyst",
  ADMIN: "admin",
});

const DASHBOARD_READ_ROLES = [ROLES.VIEWER, ROLES.ANALYST, ROLES.ADMIN];
const RECORD_READ_ROLES = [ROLES.ANALYST, ROLES.ADMIN];
const MANAGED_USER_ROLES = [ROLES.VIEWER, ROLES.ANALYST];

module.exports = {
  ROLES,
  DASHBOARD_READ_ROLES,
  RECORD_READ_ROLES,
  MANAGED_USER_ROLES,
};
